const mongoose = require("mongoose");
const WorkOrder = require("../models/WorkOrder");
const Device = require("../models/Device");
const User = require("../models/User");

// ---------------------------------------------------------------------------
// Population paths for tech orders
// ---------------------------------------------------------------------------

const TECH_POPULATE = [
  {
    path: "device",
    select: "code name type line",
    populate: {
      path: "line",
      select: "name",
      populate: {
        path: "area",
        select: "name",
        populate: { path: "plant", select: "name" },
      },
    },
  },
  { path: "tech.subtasks.subtask" },
  { path: "responsible", select: "idNumber name" },
  { path: "supervisor", select: "idNumber name" },
];

// ---------------------------------------------------------------------------
// createTechOrder
// ---------------------------------------------------------------------------

async function createTechOrder(req, res) {
  try {
    const body = req.body;

    const user = await User.findOne({ idNumber: req.tokenData.id }).lean();

    if (!body.tech) {
      return res.status(400).send({ error: "tech field is required" });
    }

    if (!body.tech.subtasks || body.tech.subtasks.length === 0) {
      return res.status(400).send({ error: "tech.subtasks must not be empty" });
    }

    if (!body.device) {
      return res.status(400).send({ error: "device is required" });
    }

    const device = await Device.findOne(
      mongoose.isValidObjectId(body.device)
        ? { _id: body.device }
        : { code: body.device },
    ).lean();
    if (!device) return res.status(404).send({ error: "Device not found" });

    const lastOrder = await WorkOrder.findOne(
      {},
      {},
      { sort: { code: -1 } },
    ).lean();
    let code = lastOrder ? lastOrder.code + 1 : 10000;

    let savedOrder = null;
    let attempts = 0;

    while (attempts < 3 && !savedOrder) {
      try {
        const newOrder = new WorkOrder({
          code,
          device: device._id,
          type: "tech",
          status: body.status || "Abierta",
          class: body.class,
          description: body.description,
          solicitor: body.solicitor,
          clientWO: body.clientWO,
          responsible: body.responsible || undefined,
          supervisor: body.supervisor || undefined,
          registration: {
            date: new Date(),
            user: body.registrationUser || undefined,
          },
          tech: {
            generatedBy: user ? user._id : undefined,
            estimatedDuration: body.tech.estimatedDuration || undefined,
            planned: body.tech.planned || undefined,
            diagnostics: body.tech.diagnostics || undefined,
            // Each entry must have { subtask: ObjectId }.
            // snapshot is generated by the pre("save") hook — do not send it.
            subtasks: body.tech.subtasks.map((st) => ({
              subtask: st.subtask,
              order: st.order,
              comments: st.comments,
              value: st.value,
            })),
          },
        });

        savedOrder = await newOrder.save();
      } catch (e) {
        if (e.code === 11000) {
          code += 1;
          attempts += 1;
        } else {
          throw e;
        }
      }
    }

    if (!savedOrder) {
      return res.status(500).send({ error: "Could not generate unique code" });
    }

    const populated = await WorkOrder.findById(savedOrder._id)
      .populate(TECH_POPULATE)
      .lean();

    return res.status(201).send(populated);
  } catch (e) {
    console.log(e);
    return res.status(400).send({ error: e.message });
  }
}

// ---------------------------------------------------------------------------
// getTechOrderById
// ---------------------------------------------------------------------------

async function getTechOrderById(req, res) {
  try {
    console.log(req.params);
    const { id } = req.params;

    if (!mongoose.isValidObjectId(id)) {
      return res.status(400).send({ error: "Invalid id" });
    }

    const doc = await WorkOrder.findOne({
      _id: id,
      type: "tech",
      "deletion.at": { $exists: false },
    })
      .populate(TECH_POPULATE)
      .lean();

    if (!doc) return res.status(404).send({ error: "Tech order not found" });

    return res.status(200).send(doc);
  } catch (e) {
    return res.status(400).send({ error: e.message });
  }
}

// ---------------------------------------------------------------------------
// getAllTechOrders
// ---------------------------------------------------------------------------

async function getAllTechOrders(req, res) {
  try {
    const limit = parseInt(req.query.limit) || 50;
    const skip = parseInt(req.query.skip) || 0;
    const filter = { type: "tech", "deletion.at": { $exists: false } };

    if (req.query.status) filter.status = req.query.status;
    if (req.query.device) filter.device = req.query.device;

    let query = WorkOrder.find(filter)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit);

    if (req.query.populate === "true") {
      query = query.populate(TECH_POPULATE);
    }

    const [docs, total] = await Promise.all([
      query.lean(),
      WorkOrder.countDocuments(filter),
    ]);

    return res.status(200).send({ total, limit, skip, data: docs });
  } catch (e) {
    return res.status(400).send({ error: e.message });
  }
}

// ---------------------------------------------------------------------------
// updateTechOrder
// ---------------------------------------------------------------------------

async function updateTechOrder(req, res) {
  try {
    const { id } = req.params;

    if (!mongoose.isValidObjectId(id)) {
      return res.status(400).send({ error: "Invalid id" });
    }

    const workOrder = await WorkOrder.findOne({
      _id: id,
      type: "tech",
      "deletion.at": { $exists: false },
    });

    if (!workOrder)
      return res.status(404).send({ error: "Tech order not found" });

    const body = req.body;

    // -- Top-level scalar fields ------------------------------------------
    if (body.status !== undefined) {
      workOrder.status = body.status;
      if (body.status === "Cerrada") {
        workOrder.closed = { date: new Date() };
        workOrder.completed = 100;
      }
    }
    if (body.description !== undefined)
      workOrder.description = body.description;
    if (body.class !== undefined) workOrder.class = body.class;
    if (body.solicitor !== undefined) workOrder.solicitor = body.solicitor;
    if (body.clientWO !== undefined) workOrder.clientWO = body.clientWO;
    if (body.responsible !== undefined)
      workOrder.responsible = body.responsible;
    if (body.supervisor !== undefined) workOrder.supervisor = body.supervisor;
    if (body.completed !== undefined) workOrder.completed = body.completed;

    // -- Tech fields --------------------------------------------------------
    if (body.tech) {
      if (body.tech.estimatedDuration !== undefined) {
        workOrder.tech.estimatedDuration = body.tech.estimatedDuration;
      }

      // Full replacement of planned and diagnostics
      if (body.tech.planned !== undefined) {
        workOrder.tech.planned = body.tech.planned;
      }

      if (body.tech.diagnostics !== undefined) {
        workOrder.tech.diagnostics = body.tech.diagnostics;
      }

      // Subtasks: replace the array, preserving existing snapshots.
      // The pre("save") hook will generate snapshots for any entry that
      // lacks one (i.e. newly added subtasks).
      if (Array.isArray(body.tech.subtasks)) {
        const existingMap = new Map(
          workOrder.tech.subtasks.map((st) => [st.subtask.toString(), st]),
        );

        workOrder.tech.subtasks = body.tech.subtasks.map((incoming) => {
          const existing = existingMap.get(incoming.subtask?.toString());
          return {
            subtask: incoming.subtask,
            // Carry the persisted snapshot forward so the hook skips re-fetch
            snapshot: existing?.snapshot ?? incoming.snapshot,
            order:
              incoming.order !== undefined ? incoming.order : existing?.order,
            comments:
              incoming.comments !== undefined
                ? incoming.comments
                : existing?.comments,
            value:
              incoming.value !== undefined ? incoming.value : existing?.value,
          };
        });
      }
    }

    await workOrder.save();

    const updated = await WorkOrder.findById(id).populate(TECH_POPULATE).lean();
    return res.status(200).send(updated);
  } catch (e) {
    console.log(e);
    return res.status(400).send({ error: e.message });
  }
}

// ---------------------------------------------------------------------------
// deleteTechOrder  (soft delete)
// ---------------------------------------------------------------------------

async function deleteTechOrder(req, res) {
  try {
    const { id } = req.params;

    if (!mongoose.isValidObjectId(id)) {
      return res.status(400).send({ error: "Invalid id" });
    }

    const workOrder = await WorkOrder.findOne({ _id: id, type: "tech" });

    if (!workOrder)
      return res.status(404).send({ error: "Tech order not found" });

    if (workOrder.deletion?.at) {
      return res.status(400).send({ error: "Tech order already deleted" });
    }

    workOrder.deletion = {
      at: new Date(),
      by: req.user._id,
    };

    await workOrder.save();

    return res.status(200).send({ message: "Tech order deleted", id });
  } catch (e) {
    return res.status(400).send({ error: e.message });
  }
}

// ---------------------------------------------------------------------------

module.exports = {
  createTechOrder,
  getTechOrderById,
  getAllTechOrders,
  updateTechOrder,
  deleteTechOrder,
};
